### ISSUE TITLE
Is it only applied to MSRC-21 dataset?

### ISSUE THREAD

**Issue by CarrieHui** [lucasb-eyer/pydensecrf#19]
Hi lucasb-eyer,
    
I am working on post-processing the output of CNN using densecrf on PASCAL VOC dataset. It seems your code doesn't works on it. Is it only applied to MSRC-21 dataset? If so, would you be willing to public your training/learning code?

Looking forward your reply. Thank you in advance.

                                                                                                                Carrie

**Comment by lucasb-eyer** [comment]
Hi, I have no idea what you're talking about for various reasons:

1. What does "doesn't work" mean? Just saying "doesn't work" is not helpful.
2. This code is completely independent of any dataset whatsoever. I don't even know MSRC-21 :)
3. Learning has not been wrapped in this code yet, as I have written in the README file.

I'm closing this issue since there is no real issue. But feel free to open a new issue with the actual error that you get and enough context for me to be able to understand it.
