### ISSUE TITLE
how combine CNN and CRF for Image segmentation?

### ISSUE THREAD

**Issue by ahukui** [lucasb-eyer/pydensecrf#33]
how combine CNN and CRF for Image segmentation?
3ks

**Comment by lucasb-eyer** [comment]
Typically this is done by having the CNN create the unaries for the DenseCRF, but other ways have been proposed too. I recommend you read a few papers about it.

Since this is not a question about the library, but about your understanding of CNNs and CRFs, I'm closing this issue. If you have a specific question regarding `pydensecrf`, feel free to re-open this issue.
