### ISSUE TITLE
ImportError: No module named densecrf

### ISSUE THREAD

**Issue by chowkamlee81** [lucasb-eyer/pydensecrf#46]
Hai,

I installed densecrf module using 
python setup.py install

It got installed succesfully. 
import pydensecrf---->works
import pydensecrf.densecrf as dcrf----> fails with Import error..

Kindly suggest how to go further

**Comment by yaxingwang** [comment]
you should put __init__.py   into the  file: densecrf.

**Comment by lucasb-eyer** [comment]
huh, that's odd, it works just fine for me, and I can't reproduce your problem, no matter what I try. I will need more info in order to help here.

@yaxingwang That file [has existed for a long time](https://github.com/lucasb-eyer/pydensecrf/blob/master/pydensecrf/__init__.py), are you somehow missing it?

**Comment by lucasb-eyer** [comment]
Also, the recommended way of installing is now through pip from the cheeseshop `pip install pydensecrf`.

**Comment by chowkamlee81** [comment]
Problem got solved since i copied .so files from /usr/loca/pydense.egg to my local directory. Iam able to retrieve the result. Thanks for your kind reply.
