### ISSUE TITLE
pip install error under windows

### ISSUE THREAD

**Issue by micklexqg** [lucasb-eyer/pydensecrf#64]
i try to install  pydensecrf under windows , but failed:
![image](https://user-images.githubusercontent.com/13776012/39341424-b556d26a-4a05-11e8-9a80-65034b53194f.png)
python version = 3.5.2
windows 7 and 64 bit
has anyone succeed?

**Comment by lucasb-eyer** [comment]
How about doing exactly what the last line tells you to do?

> error: Microsoft Visual C++ 14.0 is required. **Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools**

If you already did that, then google for this exact error and you will find quite a few trouble-shootings.

I'm closing this as so far it seems to be a problem with your system setup, not a problem with PyDenseCRF. If it turns out otherwise, please feel free to re-open the issue with more information.
